apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bar-app
  template:
    metadata:
      labels:
        app: bar-app
    spec:
      containers:
        - name: bar-app
          image: robinnagpal/argo-learning-bar-app:b98a212
          env:
            - name: APP_NAME
              value: bar
